version: 2.1
jobs:
  push:
    steps: 
      - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
      - docker tag $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME:latest registry.heroku.com/$HEROKU_APP_NAME/web
      - docker push registry.heroku.com/$HEROKU_APP_NAME/web

orbs:
  docker: circleci/docker@1.0.0
workflows:
  deploy:
    jobs:
      - docker/publish:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: 'latest'
      - push
