version: 2.1
jobs:
  push:
    machine: true
    steps: 
      - heroku/install
      - run: docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
      - run: docker pull avrj/dwd2020-simple:latest
      - run: docker tag avrj/dwd2020-simple:latest registry.heroku.com/$HEROKU_APP_NAME/web
      - run: docker push registry.heroku.com/$HEROKU_APP_NAME/web
      # "heroku container:release" does not work with the official Heroku orb

orbs:
  docker: circleci/docker@1.0.0
  heroku: circleci/heroku@1.0.1
workflows:
  deploy:
    jobs:
      - docker/publish:
          image: avrj/dwd2020-simple
          tag: 'latest'
      - push:
          requires:
            - docker/publish
